name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: NuggetTraining.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: ConsoleApp1\TestProject1\TestProject1.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: NuggetTraining    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: NuggetTraining\ConsoleApp1.csproj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Build
    - name: Build 
      run: dotnet build NuggetTraining.sln -p:Configuration=Release

      #p ack
    - name: Pack 
      run: dotnet pack --configuration Release

      
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Output (${{ matrix.configuration }})
        path: NuggetTraining\bin\Release\net9.0
